In [12]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
# Performing some operations
print("Original Array:", my_array)
print("Array multiplied by 2:", my_array * 2)
print("Array squared:", my_array ** 2)
print("Sum of elements:", np.sum(my_array))
print("Mean of elements:", np.mean(my_array))

Original Array: [1 2 3 4 5]
Array multiplied by 2: [ 2  4  6  8 10]
Array squared: [ 1  4  9 16 25]
Sum of elements: 15
Mean of elements: 3.0


In [13]:
import numpy as np
np.__version__

'2.2.3'

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3.0)

array([0., 1., 2.])

In [16]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(20,10)# 1st arg < 2nd arg

array([], dtype=int64)

In [20]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [21]:
np.arange(-16,-10)

array([-16, -15, -14, -13, -12, -11])

In [24]:
np.arange()

TypeError: arange() requires stop to be specified.

In [ ]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(3)#system given own parameter tuning

array([0., 0., 0.])

In [ ]:
np.zeros(5,dtype=int)#hyper parameter tuning

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [ ]:
zero = np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [ ]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((5,10),dtype=int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [ ]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
random.rand(3,2)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(5)

array([0.78915747, 0.94812627, 0.46610273, 0.67816922, 0.13814227])

In [ ]:
np.random.rand(3,5)

array([[0.74691709, 0.60523899, 0.30592272, 0.01579621, 0.10389904],
       [0.40305536, 0.3811479 , 0.96727477, 0.14907108, 0.63341775],
       [0.44234646, 0.44189695, 0.48983223, 0.26133667, 0.16299381]])

In [ ]:
np.random.randint(5)

1

In [ ]:
np.random.randint(1,9)

1

In [ ]:
np.random.randint(10,20,5)

array([12, 10, 15, 14, 14], dtype=int32)

In [ ]:
np.random.randint(1,6,4)

array([2, 5, 3, 3], dtype=int32)

In [ ]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [ ]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [28]:
np.random.randint(10,40,(10,10))

array([[24, 15, 31, 13, 11, 34, 36, 28, 32, 35],
       [28, 36, 32, 34, 28, 16, 38, 35, 35, 15],
       [14, 16, 27, 31, 16, 21, 12, 28, 18, 27],
       [27, 35, 17, 38, 30, 18, 37, 32, 23, 12],
       [34, 38, 23, 33, 38, 34, 14, 19, 26, 27],
       [14, 10, 25, 37, 39, 35, 25, 32, 11, 28],
       [39, 24, 19, 11, 27, 28, 34, 21, 21, 20],
       [16, 34, 36, 22, 15, 27, 16, 12, 13, 34],
       [23, 30, 30, 29, 22, 35, 33, 11, 25, 31],
       [11, 38, 11, 30, 33, 32, 22, 25, 11, 10]], dtype=int32)

In [29]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
b= np.random.randint(10,20,(5,4))
b

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19],
       [18, 13, 16, 11],
       [18, 10, 13, 14]], dtype=int32)

In [33]:
type(b)

numpy.ndarray

In [34]:
b

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19],
       [18, 13, 16, 11],
       [18, 10, 13, 14]], dtype=int32)

In [35]:
b[:]

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19],
       [18, 13, 16, 11],
       [18, 10, 13, 14]], dtype=int32)

In [38]:
b[1:3]

array([[13, 12, 12, 10],
       [15, 17, 12, 19]], dtype=int32)

In [39]:
b[1,2]

np.int32(12)

In [40]:
b[1,3]

np.int32(10)

In [42]:
b

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19],
       [18, 13, 16, 11],
       [18, 10, 13, 14]], dtype=int32)

In [68]:
b[1,-1]


np.int32(10)

In [43]:
b[1,-2]

np.int32(12)

In [44]:
b

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19],
       [18, 13, 16, 11],
       [18, 10, 13, 14]], dtype=int32)

In [45]:
b[2:3]

array([[15, 17, 12, 19]], dtype=int32)

In [46]:
b[0:-2]

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19]], dtype=int32)

In [49]:
b

array([[17, 11, 11, 16],
       [13, 12, 12, 10],
       [15, 17, 12, 19],
       [18, 13, 16, 11],
       [18, 10, 13, 14]], dtype=int32)

In [57]:
b[-4:2]

array([[13, 12, 12, 10]], dtype=int32)

In [50]:
b[-4:2]

array([[13, 12, 12, 10]], dtype=int32)

In [53]:
a=np.random.randint(10,20,10)
a

array([17, 13, 15, 16, 18, 14, 12, 10, 10, 12], dtype=int32)

In [55]:
arr2=np.random.randint(0,100,(10,10))
arr2

array([[59,  8, 86, 49, 64, 98, 64, 28, 30, 92],
       [82, 89, 54, 58, 29, 90, 24, 80, 44, 61],
       [ 2, 38, 21, 47, 86, 93, 55, 68, 28, 51],
       [92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [33, 53, 63, 34, 83, 40, 17, 16, 90, 79],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [87, 39, 63, 69, 41, 90, 45, 56, 23, 60],
       [95, 55, 47, 87, 47, 90, 10, 77, 19, 36],
       [32, 56, 75, 10, 64, 91, 78,  9, 21, 51],
       [94, 33, 54, 49, 82, 91, 58, 84, 16, 85]], dtype=int32)

In [58]:
arr2[::-1]

array([[94, 33, 54, 49, 82, 91, 58, 84, 16, 85],
       [32, 56, 75, 10, 64, 91, 78,  9, 21, 51],
       [95, 55, 47, 87, 47, 90, 10, 77, 19, 36],
       [87, 39, 63, 69, 41, 90, 45, 56, 23, 60],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [33, 53, 63, 34, 83, 40, 17, 16, 90, 79],
       [92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [ 2, 38, 21, 47, 86, 93, 55, 68, 28, 51],
       [82, 89, 54, 58, 29, 90, 24, 80, 44, 61],
       [59,  8, 86, 49, 64, 98, 64, 28, 30, 92]], dtype=int32)

In [ ]:
arr2[::-2]#step count from reverse

array([[94, 33, 54, 49, 82, 91, 58, 84, 16, 85],
       [95, 55, 47, 87, 47, 90, 10, 77, 19, 36],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [82, 89, 54, 58, 29, 90, 24, 80, 44, 61]], dtype=int32)

In [61]:
arr2

array([[59,  8, 86, 49, 64, 98, 64, 28, 30, 92],
       [82, 89, 54, 58, 29, 90, 24, 80, 44, 61],
       [ 2, 38, 21, 47, 86, 93, 55, 68, 28, 51],
       [92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [33, 53, 63, 34, 83, 40, 17, 16, 90, 79],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [87, 39, 63, 69, 41, 90, 45, 56, 23, 60],
       [95, 55, 47, 87, 47, 90, 10, 77, 19, 36],
       [32, 56, 75, 10, 64, 91, 78,  9, 21, 51],
       [94, 33, 54, 49, 82, 91, 58, 84, 16, 85]], dtype=int32)

In [60]:
arr2[:-3]

array([[59,  8, 86, 49, 64, 98, 64, 28, 30, 92],
       [82, 89, 54, 58, 29, 90, 24, 80, 44, 61],
       [ 2, 38, 21, 47, 86, 93, 55, 68, 28, 51],
       [92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [33, 53, 63, 34, 83, 40, 17, 16, 90, 79],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [87, 39, 63, 69, 41, 90, 45, 56, 23, 60]], dtype=int32)

In [62]:
arr2[3:]

array([[92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [33, 53, 63, 34, 83, 40, 17, 16, 90, 79],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [87, 39, 63, 69, 41, 90, 45, 56, 23, 60],
       [95, 55, 47, 87, 47, 90, 10, 77, 19, 36],
       [32, 56, 75, 10, 64, 91, 78,  9, 21, 51],
       [94, 33, 54, 49, 82, 91, 58, 84, 16, 85]], dtype=int32)

In [63]:
arr2

array([[59,  8, 86, 49, 64, 98, 64, 28, 30, 92],
       [82, 89, 54, 58, 29, 90, 24, 80, 44, 61],
       [ 2, 38, 21, 47, 86, 93, 55, 68, 28, 51],
       [92, 92, 44, 51, 90, 52, 71, 22, 60, 44],
       [33, 53, 63, 34, 83, 40, 17, 16, 90, 79],
       [13, 27, 68, 98, 23, 69, 13, 44,  6, 61],
       [87, 39, 63, 69, 41, 90, 45, 56, 23, 60],
       [95, 55, 47, 87, 47, 90, 10, 77, 19, 36],
       [32, 56, 75, 10, 64, 91, 78,  9, 21, 51],
       [94, 33, 54, 49, 82, 91, 58, 84, 16, 85]], dtype=int32)

In [64]:
arr2.max()

np.int32(98)

In [65]:
arr2.min()

np.int32(2)

In [66]:
from numpy import *
a= array([1,2,3,4])
a

array([1, 2, 3, 4])