In [ ]:
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
# Performing some operations
print("Original Array:", my_array)
print("Array multiplied by 2:", my_array * 2)
print("Array squared:", my_array ** 2)
print("Sum of elements:", np.sum(my_array))
print("Mean of elements:", np.mean(my_array))

Original Array: [1 2 3 4 5]
Array multiplied by 2: [ 2  4  6  8 10]
Array squared: [ 1  4  9 16 25]
Sum of elements: 15
Mean of elements: 3.0


In [1]:
import numpy as np
np.__version__

'2.2.3'

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(3.0)

array([0., 1., 2.])

In [6]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(20,10)# 1st arg < 2nd arg

array([], dtype=int64)

In [11]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [12]:
np.arange(-16,-10)

array([-16, -15, -14, -13, -12, -11])

In [13]:
np.arange()

TypeError: arange() requires stop to be specified.

In [14]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [15]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [16]:
np.arange(10,30,5,8)

TypeError: Cannot interpret '8' as a data type

In [ ]:
np.zeros(3)#tuning

array([0., 0., 0.])

In [ ]:
np.zeros(5,dtype=int)#hyper parameter tuning

array([0, 0, 0, 0, 0])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [21]:
zero = np.zeros([2,2])
print(zero)

[[0. 0.]
 [0. 0.]]


In [22]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.zeros((5,10),dtype=int)


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
np.ones(3)

array([1., 1., 1.])

In [27]:
np.ones(3,dtype=int)

array([1, 1, 1])

In [29]:
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [30]:
rand(3,2)

NameError: name 'rand' is not defined

In [31]:
random.rand(3,2)

NameError: name 'random' is not defined

In [ ]:
np.random.rand(5)

array([0.78915747, 0.94812627, 0.46610273, 0.67816922, 0.13814227])

In [37]:
np.random.rand(3,5)

array([[0.74691709, 0.60523899, 0.30592272, 0.01579621, 0.10389904],
       [0.40305536, 0.3811479 , 0.96727477, 0.14907108, 0.63341775],
       [0.44234646, 0.44189695, 0.48983223, 0.26133667, 0.16299381]])

In [49]:
np.random.randint(5)

1

In [71]:
np.random.randint(1,9)

1

In [101]:
np.random.randint(10,20,5)

array([12, 10, 15, 14, 14], dtype=int32)

In [106]:
np.random.randint(1,6,4)

array([2, 5, 3, 3], dtype=int32)

In [107]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [111]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])