In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf

<module 'tensorflow' from '/Users/gvijaykumarachary/.pyenv/versions/3.10.13/lib/python3.10/site-packages/tensorflow/__init__.py'>

In [3]:
dataset = pd.read_csv('./Churn_Modelling.csv')

In [4]:
dataset

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1


In [5]:
x= dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
dataset.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0


In [7]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [9]:
dataset.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0


In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
x[:, 2] = le.fit_transform(x[:, 2])

In [11]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), [1])],
    remainder='passthrough'
)
x = np.array(ct.fit_transform(x))

In [13]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [14]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
x = sc.fit_transform(x)
x

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(8000, 12) (2000, 12) (8000,) (2000,)


In [17]:
#Lets build ANN modle building architecture

In [18]:
ann = tf.keras.models.Sequential()# establish the layer one after another

In [19]:
# 6 nurons created -input layer
ann.add(tf.keras.layers.Dense(units=6,))

In [20]:
# Adding the activation function hiden layer-hidden layer-1
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(units=5, activation='relu'))#layer-hidden layer-2

In [22]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))#layer-hidden layer-3

In [23]:
#output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [24]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
# Fitting the ANN to the Training set
ann.fit(x_train, y_train, batch_size=32, epochs=50)

Epoch 1/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 381us/step - accuracy: 0.5364 - loss: 0.7110
Epoch 2/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 329us/step - accuracy: 0.7905 - loss: 0.5690
Epoch 3/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 328us/step - accuracy: 0.7952 - loss: 0.4509
Epoch 4/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - accuracy: 0.7967 - loss: 0.4225
Epoch 5/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - accuracy: 0.7973 - loss: 0.4196
Epoch 6/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 321us/step - accuracy: 0.7876 - loss: 0.4203
Epoch 7/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 325us/step - accuracy: 0.7893 - loss: 0.4059
Epoch 8/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 322us/step - accuracy: 0.7954 - loss: 0.4024
Epoch 9/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - accuracy: 0.8147 - loss: 0.3844
Epoch 10/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - accuracy: 0.8157 - loss: 0.3807
Epoch 11/50
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 324us/step - accuracy: 0.8202 - loss: 0.3762
Epoch 12/50
250/250 ━━━━━━━━━━

In [26]:
# Predicting the Test set results
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 494us/step


In [27]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1552   55]
 [ 226  167]]


In [28]:
# Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8595

In [29]:
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 85.95%


In [30]:
# ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# # Fitting the ANN to the Training set
# ann.fit(x_train, y_train, batch_size=32, epochs=100)
# # Predicting the Test set results
# y_pred = ann.predict(x_test)
# y_pred = (y_pred > 0.5)
# # Making the Confusion Matrix
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# # Accuracy
# from sklearn.metrics import accuracy_score
# accuracy = accuracy_score(y_test, y_pred)
# print(f'Accuracy: {accuracy * 100:.2f}%')
# .keras.backend.clear_session()  # Clear the session to free resources
